<a href="https://colab.research.google.com/github/woobin-betty/BDA/blob/main/6%EC%A3%BC%EC%B0%A8_06%2C07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

pf = pd.DataFrame(data = [[25,35,8,18],
                          [18,27,10,20],
                          [17,17,10,19],
                          [12,22,9,20],
                          [22,34,8,16]],
                  index=['윤일형','강수희','홍소희','유한빈','신수빈'],
                  columns=['중간','기말','과제','출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [4]:
pf['중간']

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [5]:
pf.중간

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [6]:
pf['출석']

윤일형    18
강수희    20
홍소희    19
유한빈    20
신수빈    16
Name: 출석, dtype: int64

In [7]:
pf[['출석']]

     출석
윤일형  18
강수희  20
홍소희  19
유한빈  20
신수빈  16

In [8]:
pf[['기말','출석','중간']]

     기말  출석  중간
윤일형  35  18  25
강수희  27  20  18
홍소희  17  19  17
유한빈  22  20  12
신수빈  34  16  22

In [9]:
pf[['기말']]

     기말
윤일형  35
강수희  27
홍소희  17
유한빈  22
신수빈  34

In [10]:
import pandas as pd

pf = pd.DataFrame(data = [[25,35,8,18],
                          [18,27,10,20],
                          [17,17,10,19],
                          [12,22,9,20],
                          [22,34,8,16]],
                  index=['윤일형','강수희','홍소희','유한빈','신수빈'],
                  columns=['중간','기말','과제','출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [11]:
pf['중간'] > 20

윤일형     True
강수희    False
홍소희    False
유한빈    False
신수빈     True
Name: 중간, dtype: bool

In [12]:
pf[pf['중간']> 20]

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

In [13]:
pf[pf['출석']>=19]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [14]:
pf[(pf['출석']>=19) & (pf['기말']>=20)]

     중간  기말  과제  출석
강수희  18  27  10  20
유한빈  12  22   9  20

In [15]:
pf.loc['윤일형']

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

In [17]:
pf.loc[['윤일형']]

     중간  기말  과제  출석
윤일형  25  35   8  18

In [19]:
pf.loc[['홍소희','윤일형']]

     중간  기말  과제  출석
홍소희  17  17  10  19
윤일형  25  35   8  18

In [20]:
pf.loc['윤일형':'유한빈']

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [21]:
pf.loc[pf.중간 > 20]

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

In [22]:
pf.loc[(pf.중간 > 10) & (pf.과제 ==10)]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19

In [23]:
pf.loc[pf.index[0]]

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

In [24]:
pf.loc[[pf.index[0]]]

     중간  기말  과제  출석
윤일형  25  35   8  18

In [25]:
pf.loc[pf.index[1:4]]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [26]:
pf.loc[pf.index[1:4]][['기말','과제']]

     기말  과제
강수희  27  10
홍소희  17  10
유한빈  22   9

In [27]:
pf.loc[:,'과제']

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

In [28]:
pf.loc[:,'중간':'과제']

     중간  기말  과제
윤일형  25  35   8
강수희  18  27  10
홍소희  17  17  10
유한빈  12  22   9
신수빈  22  34   8

In [29]:
pf.loc[:,['기말', '출석']]

     기말  출석
윤일형  35  18
강수희  27  20
홍소희  17  19
유한빈  22  20
신수빈  34  16

In [32]:
pf.loc[:,pf.columns[0]]

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [33]:
pf.loc[:, [pf.columns[0]]]

     중간
윤일형  25
강수희  18
홍소희  17
유한빈  12
신수빈  22

In [34]:
pf.loc[:,pf.columns[1:]]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

In [35]:
pf.loc[:,pf.columns[1:3]]

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9
신수빈  34   8

In [36]:
pf.loc[:,pf.columns[1:]][['기말','과제']]

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9
신수빈  34   8

In [37]:
pf.loc['윤일형', '출석']

np.int64(18)

In [38]:
pf.loc['윤일형': '유한빈', '기말']

윤일형    35
강수희    27
홍소희    17
유한빈    22
Name: 기말, dtype: int64

In [39]:
pf.loc['윤일형': '유한빈', '기말':'과제']

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9

In [41]:
pf.loc[pf.index[0], pf.columns[1]]

np.int64(35)

In [42]:
pf.loc[pf.index[0:3], pf.columns[2]]

윤일형     8
강수희    10
홍소희    10
Name: 과제, dtype: int64

In [43]:
pf.loc[pf.index[0:3], pf.columns[2:]]

     과제  출석
윤일형   8  18
강수희  10  20
홍소희  10  19

In [44]:
pf.iloc[1]

중간    18
기말    27
과제    10
출석    20
Name: 강수희, dtype: int64

In [45]:
pf.iloc[[1]]

     중간  기말  과제  출석
강수희  18  27  10  20

In [46]:
pf.iloc[[1,3]]

     중간  기말  과제  출석
강수희  18  27  10  20
유한빈  12  22   9  20

In [47]:
pf.iloc[2:]

     중간  기말  과제  출석
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [48]:
pf.iloc[:,2]

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

In [49]:
pf.iloc[:, [2]]

     과제
윤일형   8
강수희  10
홍소희  10
유한빈   9
신수빈   8

In [50]:
pf.iloc[:, 1:]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

In [51]:
pf.iloc[1,1]

np.int64(27)

In [52]:
pf.iloc[1:3, 1:]

     기말  과제  출석
강수희  27  10  20
홍소희  17  10  19

In [53]:
pf.iloc[:, 1:]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

In [54]:
pf.iloc[[1,3,4], 1:]

     기말  과제  출석
강수희  27  10  20
유한빈  22   9  20
신수빈  34   8  16

In [55]:
pf.iloc[[1,3,4], [0,1]]

     중간  기말
강수희  18  27
유한빈  12  22
신수빈  22  34

In [56]:
pf.at['윤일형', '과제']

np.int64(8)

In [57]:
pf.at['유한빈', '기말']

np.int64(22)

In [58]:
pf.at[pf.index[1], '출석']

np.int64(20)

In [59]:
pf.at[pf.index[3], pf.columns[2]]

np.int64(9)

In [60]:
pf.iat[1,2]

np.int64(10)

In [61]:
pf.iat[2,3]

np.int64(19)

In [65]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive