<a href="https://colab.research.google.com/github/woobin-betty/BDA/blob/main/7%EC%A3%BC%EC%B0%A8_ch07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
df = pd.read_csv('/content/sample_data/2016년졸음운전.csv', encoding='EUC-KR')
display(df.head())

        연월  사고(건)  사망(명)  부상(명)
0  2016년1월    192      5    387
1  2016년2월    174      6    328
2  2016년3월    217      7    435
3  2016년4월    216      7    419
4  2016년5월    239     13    522

In [14]:
df.head()

        연월  사고(건)  사망(명)  부상(명)
0  2016년1월    192      5    387
1  2016년2월    174      6    328
2  2016년3월    217      7    435
3  2016년4월    216      7    419
4  2016년5월    239     13    522

In [15]:
df.head(7)

        연월  사고(건)  사망(명)  부상(명)
0  2016년1월    192      5    387
1  2016년2월    174      6    328
2  2016년3월    217      7    435
3  2016년4월    216      7    419
4  2016년5월    239     13    522
5  2016년6월    200     12    362
6  2016년7월    227      9    460

In [16]:
df.tail()

          연월  사고(건)  사망(명)  부상(명)
7    2016년8월    230      7    490
8    2016년9월    187     13    347
9   2016년10월    183     10    367
10  2016년11월    200      5    418
11  2016년12월    168      4    364

In [17]:
df.tail(6)

          연월  사고(건)  사망(명)  부상(명)
6    2016년7월    227      9    460
7    2016년8월    230      7    490
8    2016년9월    187     13    347
9   2016년10월    183     10    367
10  2016년11월    200      5    418
11  2016년12월    168      4    364

In [18]:
df.sort_index()

          연월  사고(건)  사망(명)  부상(명)
0    2016년1월    192      5    387
1    2016년2월    174      6    328
2    2016년3월    217      7    435
3    2016년4월    216      7    419
4    2016년5월    239     13    522
5    2016년6월    200     12    362
6    2016년7월    227      9    460
7    2016년8월    230      7    490
8    2016년9월    187     13    347
9   2016년10월    183     10    367
10  2016년11월    200      5    418
11  2016년12월    168      4    364

In [19]:
df.sort_index(axis=0)

          연월  사고(건)  사망(명)  부상(명)
0    2016년1월    192      5    387
1    2016년2월    174      6    328
2    2016년3월    217      7    435
3    2016년4월    216      7    419
4    2016년5월    239     13    522
5    2016년6월    200     12    362
6    2016년7월    227      9    460
7    2016년8월    230      7    490
8    2016년9월    187     13    347
9   2016년10월    183     10    367
10  2016년11월    200      5    418
11  2016년12월    168      4    364

In [20]:
df.sort_index(ascending=False)

          연월  사고(건)  사망(명)  부상(명)
11  2016년12월    168      4    364
10  2016년11월    200      5    418
9   2016년10월    183     10    367
8    2016년9월    187     13    347
7    2016년8월    230      7    490
6    2016년7월    227      9    460
5    2016년6월    200     12    362
4    2016년5월    239     13    522
3    2016년4월    216      7    419
2    2016년3월    217      7    435
1    2016년2월    174      6    328
0    2016년1월    192      5    387

In [21]:
df.sort_index(axis=1)

    부상(명)  사고(건)  사망(명)        연월
0     387    192      5   2016년1월
1     328    174      6   2016년2월
2     435    217      7   2016년3월
3     419    216      7   2016년4월
4     522    239     13   2016년5월
5     362    200     12   2016년6월
6     460    227      9   2016년7월
7     490    230      7   2016년8월
8     347    187     13   2016년9월
9     367    183     10  2016년10월
10    418    200      5  2016년11월
11    364    168      4  2016년12월

In [22]:
df.sort_index(axis=1, ascending=False)

          연월  사망(명)  사고(건)  부상(명)
0    2016년1월      5    192    387
1    2016년2월      6    174    328
2    2016년3월      7    217    435
3    2016년4월      7    216    419
4    2016년5월     13    239    522
5    2016년6월     12    200    362
6    2016년7월      9    227    460
7    2016년8월      7    230    490
8    2016년9월     13    187    347
9   2016년10월     10    183    367
10  2016년11월      5    200    418
11  2016년12월      4    168    364

In [23]:
df.sort_values(by='사망(명)')

          연월  사고(건)  사망(명)  부상(명)
11  2016년12월    168      4    364
0    2016년1월    192      5    387
10  2016년11월    200      5    418
1    2016년2월    174      6    328
7    2016년8월    230      7    490
3    2016년4월    216      7    419
2    2016년3월    217      7    435
6    2016년7월    227      9    460
9   2016년10월    183     10    367
5    2016년6월    200     12    362
4    2016년5월    239     13    522
8    2016년9월    187     13    347

In [25]:
df.sort_values(by=['사망(명)', '부상(명)'])

          연월  사고(건)  사망(명)  부상(명)
11  2016년12월    168      4    364
0    2016년1월    192      5    387
10  2016년11월    200      5    418
1    2016년2월    174      6    328
3    2016년4월    216      7    419
2    2016년3월    217      7    435
7    2016년8월    230      7    490
6    2016년7월    227      9    460
9   2016년10월    183     10    367
5    2016년6월    200     12    362
8    2016년9월    187     13    347
4    2016년5월    239     13    522

In [27]:
df.sort_values(by='2016년12월', axis=1)

          연월  사고(건)  사망(명)  부상(명)
9   2016년10월    183     10    367
10  2016년11월    200      5    418
11  2016년12월    168      4    364
0    2016년1월    192      5    387
1    2016년2월    174      6    328
2    2016년3월    217      7    435
3    2016년4월    216      7    419
4    2016년5월    239     13    522
5    2016년6월    200     12    362
6    2016년7월    227      9    460
7    2016년8월    230      7    490
8    2016년9월    187     13    347

In [47]:
df.sort_values(by='연월', ascending=False)

KeyError: '연월'

In [30]:
import numpy as np
import pandas as pd

dates = pd.date_range("20240102", periods=6)
df = pd.DataFrame(np.arange(24).reshape(6,4), index=dates)
df

             0   1   2   3
2024-01-02   0   1   2   3
2024-01-03   4   5   6   7
2024-01-04   8   9  10  11
2024-01-05  12  13  14  15
2024-01-06  16  17  18  19
2024-01-07  20  21  22  23

In [31]:
df.columns = list('ABCD')
df

             A   B   C   D
2024-01-02   0   1   2   3
2024-01-03   4   5   6   7
2024-01-04   8   9  10  11
2024-01-05  12  13  14  15
2024-01-06  16  17  18  19
2024-01-07  20  21  22  23

In [32]:
s1 = pd.Series([1,2,3,4,5], index=pd.date_range("20240102", periods=5))
s1

2024-01-02    1
2024-01-03    2
2024-01-04    3
2024-01-05    4
2024-01-06    5
Freq: D, dtype: int64

In [33]:
df["E"] = s1
df

             A   B   C   D    E
2024-01-02   0   1   2   3  1.0
2024-01-03   4   5   6   7  2.0
2024-01-04   8   9  10  11  3.0
2024-01-05  12  13  14  15  4.0
2024-01-06  16  17  18  19  5.0
2024-01-07  20  21  22  23  NaN

In [34]:
df.loc['2024-01-02', 'A'] = 10
df

             A   B   C   D    E
2024-01-02  10   1   2   3  1.0
2024-01-03   4   5   6   7  2.0
2024-01-04   8   9  10  11  3.0
2024-01-05  12  13  14  15  4.0
2024-01-06  16  17  18  19  5.0
2024-01-07  20  21  22  23  NaN

In [35]:
df.loc[dates[1], 'B'] = 50
df

             A   B   C   D    E
2024-01-02  10   1   2   3  1.0
2024-01-03   4  50   6   7  2.0
2024-01-04   8   9  10  11  3.0
2024-01-05  12  13  14  15  4.0
2024-01-06  16  17  18  19  5.0
2024-01-07  20  21  22  23  NaN

In [36]:
df.at[dates[2], df.columns[2]] = 100
df

             A   B    C   D    E
2024-01-02  10   1    2   3  1.0
2024-01-03   4  50    6   7  2.0
2024-01-04   8   9  100  11  3.0
2024-01-05  12  13   14  15  4.0
2024-01-06  16  17   18  19  5.0
2024-01-07  20  21   22  23  NaN

In [37]:
df.at[df.index[-1], df.columns[-1]] = 230
df

             A   B    C   D      E
2024-01-02  10   1    2   3    1.0
2024-01-03   4  50    6   7    2.0
2024-01-04   8   9  100  11    3.0
2024-01-05  12  13   14  15    4.0
2024-01-06  16  17   18  19    5.0
2024-01-07  20  21   22  23  230.0

In [38]:
df.iloc[1,2] = 60
df

             A   B    C   D      E
2024-01-02  10   1    2   3    1.0
2024-01-03   4  50   60   7    2.0
2024-01-04   8   9  100  11    3.0
2024-01-05  12  13   14  15    4.0
2024-01-06  16  17   18  19    5.0
2024-01-07  20  21   22  23  230.0

In [39]:
df.iat[3,3] = 150
df

             A   B    C    D      E
2024-01-02  10   1    2    3    1.0
2024-01-03   4  50   60    7    2.0
2024-01-04   8   9  100   11    3.0
2024-01-05  12  13   14  150    4.0
2024-01-06  16  17   18   19    5.0
2024-01-07  20  21   22   23  230.0

In [40]:
df.iloc[:,4] = [500] * len(df)
df

             A   B    C    D      E
2024-01-02  10   1    2    3  500.0
2024-01-03   4  50   60    7  500.0
2024-01-04   8   9  100   11  500.0
2024-01-05  12  13   14  150  500.0
2024-01-06  16  17   18   19  500.0
2024-01-07  20  21   22   23  500.0

In [41]:
df.iloc[:,4] = 600
df

             A   B    C    D      E
2024-01-02  10   1    2    3  600.0
2024-01-03   4  50   60    7  600.0
2024-01-04   8   9  100   11  600.0
2024-01-05  12  13   14  150  600.0
2024-01-06  16  17   18   19  600.0
2024-01-07  20  21   22   23  600.0

In [43]:
import numpy as np
import pandas as pd

dates = pd.date_range("20250302", periods=7, freq='W-MON')
df = pd.DataFrame(np.arange(35).reshape(7,5), index=dates, columns=list('ABCDE'))
df

             A   B   C   D   E
2025-03-03   0   1   2   3   4
2025-03-10   5   6   7   8   9
2025-03-17  10  11  12  13  14
2025-03-24  15  16  17  18  19
2025-03-31  20  21  22  23  24
2025-04-07  25  26  27  28  29
2025-04-14  30  31  32  33  34

In [44]:
subdates = pd.date_range("20250307", periods=5, freq='W-MON')
subdates

DatetimeIndex(['2025-03-10', '2025-03-17', '2025-03-24', '2025-03-31',
               '2025-04-07'],
              dtype='datetime64[ns]', freq='W-MON')

In [48]:
s = pd.Series(np.linspace(10,17,5), index=subdates)
s

2025-03-10    10.00
2025-03-17    11.75
2025-03-24    13.50
2025-03-31    15.25
2025-04-07    17.00
Freq: W-MON, dtype: float64

In [49]:
df['F'] = s
df

             A   B   C   D   E      F
2025-03-03   0   1   2   3   4    NaN
2025-03-10   5   6   7   8   9  10.00
2025-03-17  10  11  12  13  14  11.75
2025-03-24  15  16  17  18  19  13.50
2025-03-31  20  21  22  23  24  15.25
2025-04-07  25  26  27  28  29  17.00
2025-04-14  30  31  32  33  34    NaN

In [50]:
df2 = df.copy()
df2.iloc[3,4] = np.nan
df2.iloc[1, :] = np.nan
df2

               A     B     C     D     E      F
2025-03-03   0.0   1.0   2.0   3.0   4.0    NaN
2025-03-10   NaN   NaN   NaN   NaN   NaN    NaN
2025-03-17  10.0  11.0  12.0  13.0  14.0  11.75
2025-03-24  15.0  16.0  17.0  18.0   NaN  13.50
2025-03-31  20.0  21.0  22.0  23.0  24.0  15.25
2025-04-07  25.0  26.0  27.0  28.0  29.0  17.00
2025-04-14  30.0  31.0  32.0  33.0  34.0    NaN

In [51]:
df2

               A     B     C     D     E      F
2025-03-03   0.0   1.0   2.0   3.0   4.0    NaN
2025-03-10   NaN   NaN   NaN   NaN   NaN    NaN
2025-03-17  10.0  11.0  12.0  13.0  14.0  11.75
2025-03-24  15.0  16.0  17.0  18.0   NaN  13.50
2025-03-31  20.0  21.0  22.0  23.0  24.0  15.25
2025-04-07  25.0  26.0  27.0  28.0  29.0  17.00
2025-04-14  30.0  31.0  32.0  33.0  34.0    NaN

In [52]:
pd.isna(df2)

                A      B      C      D      E      F
2025-03-03  False  False  False  False  False   True
2025-03-10   True   True   True   True   True   True
2025-03-17  False  False  False  False  False  False
2025-03-24  False  False  False  False   True  False
2025-03-31  False  False  False  False  False  False
2025-04-07  False  False  False  False  False  False
2025-04-14  False  False  False  False  False   True

In [53]:
df2.isna()

                A      B      C      D      E      F
2025-03-03  False  False  False  False  False   True
2025-03-10   True   True   True   True   True   True
2025-03-17  False  False  False  False  False  False
2025-03-24  False  False  False  False   True  False
2025-03-31  False  False  False  False  False  False
2025-04-07  False  False  False  False  False  False
2025-04-14  False  False  False  False  False   True

In [54]:
df2.isnull()

                A      B      C      D      E      F
2025-03-03  False  False  False  False  False   True
2025-03-10   True   True   True   True   True   True
2025-03-17  False  False  False  False  False  False
2025-03-24  False  False  False  False   True  False
2025-03-31  False  False  False  False  False  False
2025-04-07  False  False  False  False  False  False
2025-04-14  False  False  False  False  False   True

In [55]:
df2.count()

A    6
B    6
C    6
D    6
E    5
F    4
dtype: int64

In [56]:
df2.count(axis=1)

2025-03-03    5
2025-03-10    0
2025-03-17    6
2025-03-24    5
2025-03-31    6
2025-04-07    6
2025-04-14    5
Freq: W-MON, dtype: int64

In [58]:
s = df2.E.value_counts()
s

E
4.0     1
14.0    1
24.0    1
29.0    1
34.0    1
Name: count, dtype: int64

In [59]:
type(s)

pandas.core.series.Series

In [60]:
s[4]

np.int64(1)

In [61]:
s.values

array([1, 1, 1, 1, 1])

In [62]:
df2['D'].value_counts()

D
3.0     1
13.0    1
18.0    1
23.0    1
28.0    1
33.0    1
Name: count, dtype: int64

In [63]:
df2['D'].value_counts().to_frame()

      count
D
3.0       1
13.0      1
18.0      1
23.0      1
28.0      1
33.0      1

In [64]:
df2.E.value_counts(dropna=False)

E
NaN     2
4.0     1
14.0    1
24.0    1
29.0    1
34.0    1
Name: count, dtype: int64

In [65]:
df2.value_counts(dropna=False)

A     B     C     D     E     F
0.0   1.0   2.0   3.0   4.0   NaN      1
10.0  11.0  12.0  13.0  14.0  11.75    1
15.0  16.0  17.0  18.0  NaN   13.50    1
20.0  21.0  22.0  23.0  24.0  15.25    1
25.0  26.0  27.0  28.0  29.0  17.00    1
30.0  31.0  32.0  33.0  34.0  NaN      1
NaN   NaN   NaN   NaN   NaN   NaN      1
Name: count, dtype: int64

In [66]:
s1 = df2.value_counts()
s1

A     B     C     D     E     F
10.0  11.0  12.0  13.0  14.0  11.75    1
20.0  21.0  22.0  23.0  24.0  15.25    1
25.0  26.0  27.0  28.0  29.0  17.00    1
Name: count, dtype: int64

In [67]:
s1.index

MultiIndex([(10.0, 11.0, 12.0, 13.0, 14.0, 11.75),
            (20.0, 21.0, 22.0, 23.0, 24.0, 15.25),
            (25.0, 26.0, 27.0, 28.0, 29.0,  17.0)],
           names=['A', 'B', 'C', 'D', 'E', 'F'])

In [68]:
s1.values

array([1, 1, 1])

In [69]:
df2.dropna()

               A     B     C     D     E      F
2025-03-17  10.0  11.0  12.0  13.0  14.0  11.75
2025-03-31  20.0  21.0  22.0  23.0  24.0  15.25
2025-04-07  25.0  26.0  27.0  28.0  29.0  17.00

In [71]:
df2.dropna(axis=0)

               A     B     C     D     E      F
2025-03-17  10.0  11.0  12.0  13.0  14.0  11.75
2025-03-31  20.0  21.0  22.0  23.0  24.0  15.25
2025-04-07  25.0  26.0  27.0  28.0  29.0  17.00

In [72]:
df2.dropna(axis=0)

               A     B     C     D     E      F
2025-03-17  10.0  11.0  12.0  13.0  14.0  11.75
2025-03-31  20.0  21.0  22.0  23.0  24.0  15.25
2025-04-07  25.0  26.0  27.0  28.0  29.0  17.00

In [73]:
df2.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [2025-03-03 00:00:00, 2025-03-10 00:00:00, 2025-03-17 00:00:00, 2025-03-24 00:00:00, 2025-03-31 00:00:00, 2025-04-07 00:00:00, 2025-04-14 00:00:00]

In [74]:
df2[df.isna()] = 500
df2

               A     B     C     D     E       F
2025-03-03   0.0   1.0   2.0   3.0   4.0  500.00
2025-03-10   NaN   NaN   NaN   NaN   NaN     NaN
2025-03-17  10.0  11.0  12.0  13.0  14.0   11.75
2025-03-24  15.0  16.0  17.0  18.0   NaN   13.50
2025-03-31  20.0  21.0  22.0  23.0  24.0   15.25
2025-04-07  25.0  26.0  27.0  28.0  29.0   17.00
2025-04-14  30.0  31.0  32.0  33.0  34.0  500.00